owner: ZEROPOINTBRUH
repo: WebsiteAlarmClock

sites:
  # PTSD
  - name: Banabyte Website
    url: https://Banabyte.com
    expectedStatusCodes:
      - 200
      - 401
  - name: Banabyte CDN
    url: https://cdn.banabyte.com
    expectedStatusCodes:
      - 200
      - 401
  - name: Banabyte Panel
    url: https://panel.banabyte.com
    expectedStatusCodes:
      - 200
      - 401
  - name: Warzon
    url: https://warzon.io
    expectedStatusCodes:
      - 200
      - 401
  - name: Other
    url: https://dv.suroi.io
    expectedStatusCodes:
      - 200
      - 401


status-website:
  cname: status2.banabyte.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: THE PTSD ALARM CLOCK
  introTitle: "Something isn't working?"
  introMessage: Join the [Discord](https://discord.banabyte.com) to report it!
  theme: dark

commitMessages:
  commitAuthorName: "ZEROPOINTBRUH"
  commitAuthorEmail: "wegj1@hotmail.com"

assignees:
  - ZEROPOINTBRUH
