owner: ZEROPOINTBRUH
repo: WebsiteAlarmClock

sites:
  # Its not real butter
  - name: Banabyte Website
    url: https://Banabyte.com
    expectedStatusCodes:
      - 200
      - 401
  - name: Banabyte CDN
    url: https://cdn.banabyte.com
    expectedStatusCodes:
      - 200
      - 401
  - name: Banabyte Panel
    url: https://panel.banabyte.com
    expectedStatusCodes:
      - 200
      - 401
  - name: Warzon.io
    url: https://warzon.io
    expectedStatusCodes:
      - 200
      - 401
  - name: DamienVespers Private Suroi Server
    url: https://dv.suroi.io
    expectedStatusCodes:
      - 200
      - 401
  - name: DNS SERVER 1
    url: https://1.1.1.1
    expectedStatusCodes:
      - 200
      - 401
  - name: DNS SERVER 2
    url: https://dns.google
    expectedStatusCodes:
      - 200
      - 401
  - name: Cluster 1
    url: https://co-us01.banabyte.com:2021
    expectedStatusCodes:
      - 200
      - 401
  - name: Cluster 2
    url: https://co-us02.banabyte.com:2031
    expectedStatusCodes:
      - 200
      - 401
  - name: Cluster 3
    url: https://co-us03.banabyte.com:2041
    expectedStatusCodes:
      - 200
      - 401
  - name: Unknown
    url: https://admin.banabyte.com
    expectedStatusCodes:
      - 200
      - 401
  - name: BanaBlock.net
    url: https://banablock.net
    expectedStatusCodes:
      - 200
      - 401
  - name: Donetsk.live
    url: https://donetsk.live
    expectedStatusCodes:
      - 200
      - 401
  - name: Support.Donetsk.live
    url: https://support.donetsk.live
    expectedStatusCodes:
      - 200
      - 401



status-website:
  cname: status2.banabyte.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: WebsiteAlarmClock
  introTitle: "Something isn't working?"
  introMessage: Join the [Discord](https://discord.banabyte.com) to report it!
  theme: dark

commitMessages:
  commitAuthorName: "ZEROPOINTBRUH"
  commitAuthorEmail: "wegj1@hotmail.com"

assignees:
  - ZEROPOINTBRUH
